"""Regression tests for ``scripts/check_public_hygiene.py``.

These tests pin the regex behavior of the public hygiene scanner — both
that it still catches real private tokens and that it does not flag
in-source identifiers that merely happen to share substrings with home-
path prefixes (e.g. ``Roles/Users/Groups``).
"""

from __future__ import annotations

import importlib.util
import re
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[1]


def _load_hygiene_module():
    """Import ``scripts/check_public_hygiene.py`` despite the hyphenated path."""

    path = _REPO_ROOT / "scripts" / "check_public_hygiene.py"
    spec = importlib.util.spec_from_file_location("check_public_hygiene", path)
    assert spec, "could not locate scripts/check_public_hygiene.py"
    assert spec.loader, "could not locate scripts/check_public_hygiene.py"
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _posix_home_path_regex() -> re.Pattern[str]:
    module = _load_hygiene_module()
    for label, pattern, is_regex in module.DEFAULT_FORBIDDEN_TOKENS:
        if label == "posix-home-path":
            assert is_regex, "posix-home-path entry must be a regex"
            return re.compile(pattern)
    raise AssertionError("posix-home-path token entry missing from DEFAULT_FORBIDDEN_TOKENS")


def test_posix_home_path_detects_users_prefix() -> None:
    rgx = _posix_home_path_regex()
    assert rgx.search("/Users/alice/private")


def test_posix_home_path_detects_home_prefix() -> None:
    rgx = _posix_home_path_regex()
    assert rgx.search("/home/alice/private")


def test_posix_home_path_detects_inside_comment_with_leading_space() -> None:
    rgx = _posix_home_path_regex()
    assert rgx.search("# leak: /Users/bob/secret.json")


def test_posix_home_path_skips_identifier_prefixed_path_segment() -> None:
    """Prose like ``Roles/Users/Groups`` must NOT be flagged."""

    rgx = _posix_home_path_regex()
    assert rgx.search("Inline policies on Roles/Users/Groups.") is None


def test_posix_home_path_skips_identifier_prefixed_home_segment() -> None:
    rgx = _posix_home_path_regex()
    assert rgx.search("foo/home/bar baz") is None


# --- forbidden tracked filenames -------------------------------------------------
#
# Content scanning cannot catch an assistant instruction file: it is ordinary prose,
# so every token regex passes. CLAUDE.md was tracked and public for a month while this
# scanner reported OK. These tests pin the filename layer that closes that gap.


def test_agent_instruction_filenames_are_forbidden() -> None:
    module = _load_hygiene_module()
    for name in ("CLAUDE.md", "AGENTS.md", "GEMINI.md", ".cursorrules"):
        assert name in module.FORBIDDEN_TRACKED_FILENAMES, f"{name} must never be tracked"


def test_ordinary_project_files_are_not_forbidden() -> None:
    """The filename deny-list must not swallow legitimate root documents."""

    module = _load_hygiene_module()
    for name in ("README.md", "SECURITY.md", "CONTRIBUTING.md", "GOVERNANCE.md", "LICENSE"):
        assert name not in module.FORBIDDEN_TRACKED_FILENAMES


def test_forbidden_filename_would_be_caught(tmp_path: Path) -> None:
    """Mutation check: plant the file and confirm main() actually fails.

    Without this the deny-list could be an unreferenced constant and every other
    assertion here would still pass.
    """

    import subprocess

    subprocess.run(["git", "init", "-q", str(tmp_path)], check=True)
    (tmp_path / "CLAUDE.md").write_text("Standing authorization for the assistant.\n", encoding="utf-8")
    (tmp_path / "README.md").write_text("A normal file.\n", encoding="utf-8")

    module = _load_hygiene_module()
    assert module.main(["--root", str(tmp_path)]) == 1, "a tracked CLAUDE.md must fail the gate"

    (tmp_path / "CLAUDE.md").unlink()
    assert module.main(["--root", str(tmp_path)]) == 0, "the same tree without it must pass"


def test_a_generated_lock_may_not_record_the_path_it_was_compiled_from(tmp_path: Path) -> None:
    """Five committed locks named a build scratch directory and the scanner reported OK.

    ``uv pip compile`` writes its invocation into the header and names its input beside every
    requirement, so whatever path the maintainer typed is recorded verbatim. The locks carried
    ``C:/v/pins/work/<name>.in`` for the nine days they were public. Every content rule in the
    scanner asks about a HOME directory, and a build scratch root is not one.
    """

    module = _load_hygiene_module()
    requirements = tmp_path / ".github" / "requirements"
    requirements.mkdir(parents=True)
    # Built line by line: the first attempt used adjacent string literals with a `+` in the
    # middle, which binds tighter than the implicit concatenation around it and silently
    # merged two lines, so the assertion pinned the wrong line numbers.
    lines = [
        "# This file was autogenerated by uv via the following command:",
        "#    uv pip compile C:/v/pins/work/leaky.in --generate-hashes -o .github/requirements/leaky.txt",
        "zizmor==1.29.0 \\",
        "    --hash=sha256:" + "0" * 64,
        "    # via -r C:/v/pins/work/leaky.in",
    ]
    (requirements / "leaky.txt").write_text("\n".join(lines) + "\n", encoding="utf-8")

    found = module._generated_lock_violations(tmp_path)

    assert [line for _rel, line, _text in found] == [2, 5], f"expected the header and the `via` comment, got {found!r}"
    assert all(rel == ".github/requirements/leaky.txt" for rel, _line, _text in found)


def test_a_posix_build_root_counts_too(tmp_path: Path) -> None:
    """The leak was spelled with a drive letter; the same file generated on Linux must fail."""

    module = _load_hygiene_module()
    requirements = tmp_path / ".github" / "requirements"
    requirements.mkdir(parents=True)
    (requirements / "posix.txt").write_text("    # via -r /home/builder/pins/posix.in\n", encoding="utf-8")

    assert len(module._generated_lock_violations(tmp_path)) == 1


def test_a_lock_that_names_only_relative_inputs_is_clean(tmp_path: Path) -> None:
    """The other half. A rule that fired on the repaired file would be unusable."""

    module = _load_hygiene_module()
    requirements = tmp_path / ".github" / "requirements"
    requirements.mkdir(parents=True)
    (requirements / "clean.txt").write_text(
        "# This file was autogenerated by uv via the following command:\n"
        "#    uv pip compile .github/requirements/clean.in --generate-hashes\n"
        "zizmor==1.29.0 \\n"
        "    --hash=sha256:" + "0" * 64 + "\n"
        "    # via -r .github/requirements/clean.in\n",
        encoding="utf-8",
    )

    assert module._generated_lock_violations(tmp_path) == []


def test_the_repository_s_own_locks_are_clean() -> None:
    """The state this guard exists to hold, asserted against the real files."""

    module = _load_hygiene_module()
    assert module._generated_lock_violations(_REPO_ROOT) == []


def test_a_repository_with_no_lock_directory_is_not_an_error() -> None:
    module = _load_hygiene_module()
    assert module._generated_lock_violations(Path(__file__).resolve().parent) == []


def test_every_allowlisted_path_still_exists() -> None:
    """An allowlist entry for a file that is gone is a standing exemption for its name.

    ``ALLOWLISTED_PATHS`` is a whole-file skip keyed by exact relative path: ``_scan_file``
    returns ``[]`` before it reads a byte. ``tests/application/test_reports_v1_schema.py`` was
    deleted in v9.0.0 with the pre-2.0 report contracts (ADR-043) and its entry stayed behind
    through every release since. Nothing failed, because a path that matches no file skips no
    file -- until something is created at that path again, at which point the scanner would
    walk past it in silence. The entry is removed; this keeps the next one from lingering.
    """

    module = _load_hygiene_module()
    missing = sorted(p for p in module.ALLOWLISTED_PATHS if not (_REPO_ROOT / p).exists())
    assert not missing, (
        f"scripts/check_public_hygiene.py allowlists paths that do not exist: {missing}. "
        "Each is a pre-approved skip waiting for a file of that name. Delete the entry, or "
        "point it at the file that replaced it."
    )


def test_the_allowlist_is_not_empty() -> None:
    """A sweep over an empty allowlist would pass for the wrong reason."""

    module = _load_hygiene_module()
    assert len(module.ALLOWLISTED_PATHS) >= 5
