"""File-system execution for the ``init`` CLI command.

Given an :class:`InitPlan` produced by :mod:`init_planner`, this module
writes (or refuses to overwrite) every artifact the user requested:

- ``oss-policy-kit.yaml`` — persisted project configuration.
- ``waivers.yaml`` — minimal stub aligned with the templates folder.
- ``.oss-policy-kit/evidence/`` — scaffolded via the existing
  :func:`scaffold_evidence_files`, which already handles per-platform
  template selection and ``--force`` semantics.
- ``.github/workflows/oss-policy-check.yml`` — copied from the bundled
  workflow templates.

Outcomes are reported via :class:`InitOutcome`, which mirrors the shape
already used by ``scaffold-evidence`` (``created`` / ``skipped`` /
``overwritten`` lists) so the human and JSON renderers can reuse the same
pattern.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime
from importlib import resources
from pathlib import Path

from oss_policy_kit.application.evidence_scaffold import (
    ScaffoldEvidenceResult,
    scaffold_evidence_files,
)
from oss_policy_kit.application.init_planner import (
    CONFIG_FILENAME,
    CONFIG_SCHEMA_VERSION,
    GITHUB_WORKFLOW_FILENAME,
    WAIVERS_FILENAME,
    InitPlan,
)
from oss_policy_kit.domain.errors import InvalidInputError

GENERATOR_LABEL_PREFIX = "oss-policy-kit init"

_WORKFLOW_TEMPLATE_PACKAGE = "oss_policy_kit.data.templates.workflows"
_WORKFLOW_TEMPLATE_REPO_PATH = Path("templates") / "workflows"

_WORKFLOW_SOURCE_BY_DEST: dict[str, str] = {
    "oss-policy-check.yml": "github-oss-policy-check.yml",
    "oss-policy-check-with-waivers.yml": "github-oss-policy-check-with-waivers.yml",
    "oss-policy-check-level-2.yml": "github-oss-policy-check-level-2.yml",
}


@dataclass(slots=True)
class InitOutcome:
    """Summary of every filesystem action the writer took.

    Each list contains absolute :class:`Path` objects so the renderer can
    print stable, copy/paste-friendly locations regardless of CWD.
    """

    created: list[Path] = field(default_factory=list)
    skipped: list[Path] = field(default_factory=list)
    overwritten: list[Path] = field(default_factory=list)
    evidence_outcome: ScaffoldEvidenceResult | None = None
    next_steps: list[str] = field(default_factory=list)


def _now_iso_utc() -> str:
    """Return an ISO 8601 timestamp in UTC with a ``Z`` suffix."""

    return datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")


def _kit_version() -> str:
    """Best-effort version lookup for the embedded ``generator`` label."""

    try:
        from importlib.metadata import version

        return version("oss-policy-kit")
    except Exception:  # noqa: BLE001
        return "unknown"


def _render_config_yaml(plan: InitPlan) -> str:
    """Render ``oss-policy-kit.yaml`` from a plan.

    Hand-rolling the YAML keeps the diff stable and easy to read: PyYAML's
    default dumper would re-flow the file on every run.
    """

    lines = [
        "# oss-policy-kit configuration",
        f"# Generated by `{GENERATOR_LABEL_PREFIX}` on {_now_iso_utc()}.",
        "# Edit freely; future kit versions will read this file when --profile is omitted.",
        "",
        f"schema_version: {CONFIG_SCHEMA_VERSION}",
        f"profile: {plan.profile}",
        f"profile_source: {plan.profile_source}",
        f"fail_on: {plan.fail_on}",
        f'output_dir: "{plan.output_dir}"',
        'report_json_contract: "1.0"',
        "",
        "detected:",
        f"  platform: {plan.platform}",
    ]
    if plan.primary_stack is not None:
        lines.append(f'  primary_stack: "{plan.primary_stack}"')
    else:
        lines.append("  primary_stack: null")
    if plan.signals:
        lines.append("  signals:")
        for sig in plan.signals:
            lines.append(f"    - {sig}")
    else:
        lines.append("  signals: []")
    lines.extend(
        [
            "",
            f"generated_at: {_now_iso_utc()}",
            f"generator: {GENERATOR_LABEL_PREFIX} ({_kit_version()})",
            "",
        ]
    )
    return "\n".join(lines)


def _render_waivers_stub() -> str:
    """Return a minimal ``waivers.yaml`` stub compatible with the parser."""

    return (
        "# oss-policy-kit waivers\n"
        "# Each entry must have: control_id, owner, reason, expires_on (YYYY-MM-DD).\n"
        "# Waived findings remain visible in reports but stop tripping --fail-on.\n"
        "# Remove or update entries before the expires_on date.\n"
        "\n"
        "waivers: []\n"
        "\n"
        "# Example (uncomment and adjust):\n"
        "# waivers:\n"
        "#   - control_id: GH-PIN-007\n"
        "#     owner: appsec-team\n"
        "#     reason: Pinned-by-tag is acceptable for internal-only repository.\n"
        "#     expires_on: 2026-12-31\n"
    )


def _resolve_workflow_template(dest_filename: str) -> tuple[str, str]:
    """Map a destination filename to its source template name and body."""

    source = _WORKFLOW_SOURCE_BY_DEST.get(dest_filename)
    if source is None:
        raise InvalidInputError(
            f"Unknown workflow template: {dest_filename}. "
            f"Supported: {', '.join(sorted(_WORKFLOW_SOURCE_BY_DEST))}.",
        )

    try:
        ref = resources.files(_WORKFLOW_TEMPLATE_PACKAGE).joinpath(source)
        if ref.is_file():
            return source, ref.read_text(encoding="utf-8")
    except (ModuleNotFoundError, FileNotFoundError):
        pass

    repo_local = _WORKFLOW_TEMPLATE_REPO_PATH / source
    if repo_local.is_file():
        return source, repo_local.read_text(encoding="utf-8")

    raise InvalidInputError(
        f"Workflow template not found: {source}. "
        f"Expected under packaged data or {_WORKFLOW_TEMPLATE_REPO_PATH}/.",
    )


def _record_dry_run_action(path: Path, force: bool, outcome: InitOutcome) -> None:
    """Append ``path`` to the matching outcome bucket for a dry-run."""

    resolved = path.resolve()
    if not path.exists():
        outcome.created.append(resolved)
    elif force:
        outcome.overwritten.append(resolved)
    else:
        outcome.skipped.append(resolved)


def _write_text_idempotent(
    *,
    path: Path,
    body: str,
    force: bool,
    outcome: InitOutcome,
) -> None:
    """Write ``body`` to ``path`` honoring ``force``; updates ``outcome``."""

    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and not force:
        outcome.skipped.append(path.resolve())
        return
    existed = path.exists()
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(body, encoding="utf-8")
    tmp.replace(path)
    if existed:
        outcome.overwritten.append(path.resolve())
    else:
        outcome.created.append(path.resolve())


def execute_init_plan(plan: InitPlan) -> InitOutcome:
    """Execute (or dry-run) an :class:`InitPlan`."""

    outcome = InitOutcome()

    config_path = plan.target / CONFIG_FILENAME
    waivers_path = plan.target / WAIVERS_FILENAME
    evidence_dir = plan.target / ".oss-policy-kit" / "evidence"
    workflow_path = plan.target / ".github" / "workflows" / plan.workflow_filename

    if plan.dry_run:
        if plan.write_config:
            _record_dry_run_action(config_path, plan.force, outcome)
        if plan.write_waivers:
            _record_dry_run_action(waivers_path, plan.force, outcome)
        if plan.scaffold_evidence:
            outcome.created.append(evidence_dir.resolve())
        if plan.write_workflow:
            _record_dry_run_action(workflow_path, plan.force, outcome)
        outcome.next_steps = _build_next_steps(plan)
        return outcome

    if plan.write_config:
        _write_text_idempotent(
            path=config_path,
            body=_render_config_yaml(plan),
            force=plan.force,
            outcome=outcome,
        )

    if plan.write_waivers:
        _write_text_idempotent(
            path=waivers_path,
            body=_render_waivers_stub(),
            force=plan.force,
            outcome=outcome,
        )

    if plan.scaffold_evidence and plan.platform in {"github", "azure", "aws"}:
        scaffold = scaffold_evidence_files(plan.target, plan.platform, force=plan.force)
        outcome.evidence_outcome = scaffold
        outcome.created.extend(scaffold.created)
        outcome.skipped.extend(scaffold.skipped)
        outcome.overwritten.extend(scaffold.overwritten)

    if plan.write_workflow:
        _, body = _resolve_workflow_template(plan.workflow_filename)
        _write_text_idempotent(
            path=workflow_path,
            body=body,
            force=plan.force,
            outcome=outcome,
        )

    outcome.next_steps = _build_next_steps(plan)
    return outcome


def _build_next_steps(plan: InitPlan) -> list[str]:
    """Generate user-facing next steps tailored to the resulting plan."""

    steps: list[str] = []
    steps.append(
        f"Review {CONFIG_FILENAME} and adjust profile, fail_on, or output_dir as needed.",
    )
    steps.append(
        f"Run: oss-policy-kit evaluate --target . --profile {plan.profile} --fail-on {plan.fail_on}",
    )
    if plan.scaffold_evidence:
        steps.append(
            "Fill the scaffolded evidence files under .oss-policy-kit/evidence/ before relying on results.",
        )
    if plan.write_workflow and plan.platform == "github":
        steps.append(
            f"Commit .github/workflows/{GITHUB_WORKFLOW_FILENAME} to enable continuous "
            "baseline checks on pull requests.",
        )
    if plan.write_waivers:
        steps.append(
            "Add real entries to waivers.yaml (owner, reason, expires_on) only when remediation is deferred.",
        )
    if plan.platform == "unknown":
        steps.append(
            "No CI platform was detected; pass --platform or add CI workflows before running evaluate.",
        )
    return steps
