#!/usr/bin/env python3
"""Regenerate gitpage/parts/catalog-data.jsx from the bundled catalog + profiles.

The GitHub Pages landing page ships a client-side, filterable control catalog
(``ControlCatalogSection`` in ``gitpage/parts/catalog-explorer.jsx``). That
component reads ``window.CATALOG_DATA``, which is emitted by this script so the
page can never silently drift from the authoritative control set in
``src/oss_policy_kit/data/controls/catalog.yaml`` and the bundled profiles.

    python scripts/generate-gitpage-catalog-data.py            # rewrite in place
    python scripts/generate-gitpage-catalog-data.py --check    # exit 1 if stale

After regenerating, rebuild the page bundle so the data lands in bundle.js:

    cd gitpage && npm run build
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from oss_policy_kit.application.loader import (
    bundled_kit_root,
    load_catalog,
    load_profile_by_id,
)

_REPO_ROOT = Path(__file__).resolve().parents[1]
_OUT_PATH = _REPO_ROOT / "gitpage" / "parts" / "catalog-data.jsx"

# Stable display order for the assurance facet (strongest proof first).
_ASSURANCE_ORDER = ("deterministic", "evidence-backed", "signal")
_LIFECYCLE_ORDER = ("stable", "experimental", "deprecated")


def _profile_ids(root: Path) -> list[str]:
    return sorted(p.name for p in (root / "profiles").iterdir() if (p / "profile.yaml").is_file())


def _ordered(values: set[str], preferred: tuple[str, ...]) -> list[str]:
    """Preferred-order items first, then any extras alphabetically."""
    known = [v for v in preferred if v in values]
    extra = sorted(v for v in values if v not in preferred)
    return known + extra


def _build_payload() -> dict:
    root = bundled_kit_root()
    catalog = load_catalog(root / "controls" / "catalog.yaml")
    profile_ids = _profile_ids(root)

    membership: dict[str, list[str]] = {cid: [] for cid in catalog}
    for pid in profile_ids:
        spec = load_profile_by_id(root, pid)
        for cid in spec.control_ids:
            if cid in membership:
                membership[cid].append(pid)

    controls = []
    categories: set[str] = set()
    assurances: set[str] = set()
    lifecycles: set[str] = set()
    for cid, spec in catalog.items():
        categories.add(spec.category)
        assurances.add(spec.assurance)
        lifecycles.add(spec.lifecycle)
        controls.append(
            {
                "id": cid,
                "title": spec.title,
                "category": spec.category,
                "assurance": spec.assurance,
                "lifecycle": spec.lifecycle,
                "weight": spec.weight,
                "profiles": sorted(membership[cid]),
            }
        )

    return {
        "controlCount": len(controls),
        "profileCount": len(profile_ids),
        "facets": {
            "categories": sorted(categories),
            "assurances": _ordered(assurances, _ASSURANCE_ORDER),
            "lifecycles": _ordered(lifecycles, _LIFECYCLE_ORDER),
            "profiles": profile_ids,
        },
        "controls": controls,
    }


def _render(payload: dict) -> str:
    body = json.dumps(payload, indent=2, ensure_ascii=False)
    return (
        "// AUTO-GENERATED by scripts/generate-gitpage-catalog-data.py — do not edit by hand.\n"
        "// Regenerate with: python scripts/generate-gitpage-catalog-data.py\n"
        "// Source of truth: src/oss_policy_kit/data/controls/catalog.yaml + bundled profiles.\n"
        f"window.CATALOG_DATA = {body};\n"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if the file is out of date.")
    args = parser.parse_args(argv)

    content = _render(_build_payload())
    if args.check:
        current = _OUT_PATH.read_text(encoding="utf-8") if _OUT_PATH.is_file() else ""
        if current.strip() != content.strip():
            print(
                f"{_OUT_PATH} is out of date; run scripts/generate-gitpage-catalog-data.py "
                "and rebuild the gitpage bundle.",
                file=sys.stderr,
            )
            return 1
        print(f"{_OUT_PATH} is up to date.")
        return 0
    _OUT_PATH.write_text(content, encoding="utf-8")
    print(f"Wrote {_OUT_PATH} ({_build_payload()['controlCount']} controls)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
