"""``oss-policy-kit export-policy`` subcommand (ADR-035, v7.0.0).

Renders a **profile + catalog** (the policy *definition*) into a best-effort
policy **skeleton** for an external engine:

- ``--format rego`` — an OPA/Conftest policy (package ``osspolicykit``), one
  ``deny`` rule per profile control plus an aggregate ``allow``.
- ``--format cel`` — a Kyverno/CEL rule set, one boolean expression per control
  plus an aggregate ``all(...)`` expression.

This is an **integration shim, not a reimplementation** (ADR-035, the core of
the decision). The generated rules check the kit's *own output*: the caller
feeds a prior ``evaluation-report.json`` (reports/2.0 contract) as the engine
input, and the rules assert that every control the profile expects is present
and in a passing state. They do **not** re-implement the kit's
file/workflow/SARIF analysis (the 212 evaluators) — a static rule cannot
reproduce that, and pretending otherwise would be dishonest. Each generated
file states this fidelity boundary in its header.

Distinct from ``export-evidence`` (ADR-012), which consumes a *report*; this
command consumes a *profile*. Different inputs → different subcommand keeps both
contracts clean.

Properties: generated, read-only, deterministic (controls sorted by id),
byte-stable, no network. ``--validate`` runs a lightweight syntactic check
(package/header present, balanced blocks); deep semantic validation is the
target engine's job (``opa check``, ``conftest verify``).

See ``docs/policy-export.md`` for adopter guidance and ADR-035 for rationale.
"""

from __future__ import annotations

import json
from collections.abc import Callable
from pathlib import Path

import typer

from oss_policy_kit.application.loader import (
    ControlSpec,
    ProfileSpec,
    load_catalog,
    load_profile_by_id,
    merge_kit_root,
)
from oss_policy_kit.cli.common import app, exit_for_unexpected, markup_safe, stderr_console, write_stdout_text
from oss_policy_kit.cli.help_text import CMD_PANEL_EXPORT
from oss_policy_kit.domain.errors import InvalidInputError, OssPolicyKitError

_SUPPORTED_FORMATS: tuple[str, ...] = ("rego", "cel")

_DEFAULT_OUTPUT_BY_FORMAT: dict[str, Path] = {
    "rego": Path("policy.rego"),
    "cel": Path("policy.cel"),
}

# reports/2.0 control ``state`` values the generated gate treats as satisfied.
# FAIL and UNKNOWN (manual-review-required, error, skipped, waived) are NOT
# satisfied. Mirrors the kit's own ``--fail-on fail`` posture: a deterministic
# negative blocks; anything else acceptable passes the shim. Documented in the
# generated header so the consumer can tighten it (e.g. drop SELF_ATTESTED).
_PASSING_STATES: tuple[str, ...] = ("PASS", "ATTESTED", "SELF_ATTESTED", "NOT_APPLICABLE")


def _one_line(text: str) -> str:
    """Collapse whitespace so a control title is safe inside a single-line comment."""
    return " ".join(text.split())


def _sorted_profile_control_ids(profile: ProfileSpec) -> list[str]:
    """Deterministic, de-duplicated control ids for byte-stable output."""
    return sorted(set(profile.control_ids))


# --- Rego (OPA / Conftest) --------------------------------------------------


def _rego_header_lines(profile: ProfileSpec, count: int) -> list[str]:
    return [
        "# Generated by oss-policy-kit export-policy (ADR-035). DO NOT EDIT BY HAND.",
        f"# Regenerate: oss-policy-kit export-policy --profile {_one_line(profile.id)} --format rego",
        "#",
        "# FIDELITY BOUNDARY (read this):",
        "#   These rules check the kit's OWN output. `input` MUST be an oss-policy-kit",
        "#   evaluation-report.json on the reports/2.0 contract: an object with a",
        "#   `controls` array of {id, state, ...}. The rules assert that every control",
        "#   this profile expects is present and in a passing state. They do NOT",
        "#   re-implement the kit's file/workflow/SARIF analysis (the evaluators) — a",
        "#   static rule cannot reproduce that. Produce the input with:",
        f"#     oss-policy-kit evaluate --target <repo> --profile {_one_line(profile.id)} --report-json-contract 2.0",
        "#   Deep semantic validation is OPA's job: `opa check`, `conftest verify`.",
        "#",
        # Both halves collapsed. The title was already; the id was not, and a newline in it
        # put text at the start of a line, outside the comment, in three places.
        f"# Profile: {_one_line(profile.id)} — {_one_line(profile.title)}",
        f"# Controls: {count} (sorted by id)",
    ]


def _policy_string(value: str) -> str:
    """*value* as a quoted string literal for Rego or CEL, escaped.

    Both languages take JSON string syntax, so `json.dumps` is exactly the right primitive and
    there is no second escaping rule to keep in step with a hand-written one.

    This exists because the id used to be interpolated raw. A profile is allowed to name any
    string as a control (the schema constrains `controls` items only to a non-empty string), the
    profile can come from a path the adopter passes to `--profile`, and the output is executed by
    another engine in a gate. An id carrying a double quote therefore closed the literal and
    turned the remainder into policy:

        not control_satisfied("C-1" ; allow := true #")

    A newline did the same to the surrounding comment and rule. Neither was caught, because
    `--validate` counted braces.
    """

    return json.dumps(value)


def _render_rego(profile: ProfileSpec, catalog: dict[str, ControlSpec]) -> str:
    ids = _sorted_profile_control_ids(profile)
    states_set = "{" + ", ".join(_policy_string(state) for state in _PASSING_STATES) + "}"
    lines: list[str] = []
    lines.extend(_rego_header_lines(profile, len(ids)))
    lines += [
        "package osspolicykit",
        "",
        "import rego.v1",
        "",
        "# reports/2.0 control states the gate accepts as satisfied (see header).",
        f"passing_states := {states_set}",
        "",
        "# True when control `id` is present in the supplied report with a passing state.",
        "control_satisfied(id) if {",
        "\tsome c in input.controls",
        "\tc.id == id",
        "\tc.state in passing_states",
        "}",
        "",
        "# --- One deny rule per profile control (sorted by id) ---",
    ]
    for cid in ids:
        spec = catalog.get(cid)
        # `_one_line` on the fallback too: when the control is not in the catalogue the id
        # itself becomes the title, and an id carrying a newline then broke out of the
        # single-line comment and the rest of the file parsed as code.
        title = _one_line(spec.title) if spec is not None else _one_line(cid)
        assurance = spec.assurance if spec is not None else "unknown"
        lines += [
            "",
            f"# {_one_line(cid)} — {title} [assurance={assurance}]",
            "deny contains msg if {",
            f"\tnot control_satisfied({_policy_string(cid)})",
            "\tmsg := "
            + _policy_string(f"{cid} not satisfied: control missing or not in a passing state in the supplied report"),
            "}",
        ]
    lines += [
        "",
        "# Aggregate gate: allow only when no profile control was denied.",
        "default allow := false",
        "",
        "allow if count(deny) == 0",
    ]
    return "\n".join(lines) + "\n"


# --- CEL (Kyverno / cel-go) -------------------------------------------------


def _cel_header_lines(profile: ProfileSpec, count: int) -> list[str]:
    return [
        "# Generated by oss-policy-kit export-policy (ADR-035). DO NOT EDIT BY HAND.",
        f"# Regenerate: oss-policy-kit export-policy --profile {_one_line(profile.id)} --format cel",
        "#",
        "# FIDELITY BOUNDARY (read this):",
        "#   Each expression checks the kit's OWN output. Bind the CEL variable",
        "#   `report` to an oss-policy-kit evaluation-report.json on the reports/2.0",
        "#   contract: {controls: [{id, state, ...}]}. These expressions assert that",
        "#   every control this profile expects is present and passing; they do NOT",
        "#   re-implement the kit's analysis. Validate semantics in your CEL host",
        "#   (Kyverno, cel-go, etc.).",
        "#",
        f"# Profile: {_one_line(profile.id)} — {_one_line(profile.title)}",
        f"# Controls: {count} (sorted by id). One expression per control, then an aggregate.",
        "# Each non-comment line is a standalone CEL boolean expression.",
    ]


def _render_cel(profile: ProfileSpec, catalog: dict[str, ControlSpec]) -> str:
    ids = _sorted_profile_control_ids(profile)
    states_list = "[" + ", ".join(_policy_string(state) for state in _PASSING_STATES) + "]"
    lines: list[str] = []
    lines.extend(_cel_header_lines(profile, len(ids)))
    for cid in ids:
        spec = catalog.get(cid)
        # `_one_line` on the fallback too: when the control is not in the catalogue the id
        # itself becomes the title, and an id carrying a newline then broke out of the
        # single-line comment and the rest of the file parsed as code.
        title = _one_line(spec.title) if spec is not None else _one_line(cid)
        assurance = spec.assurance if spec is not None else "unknown"
        lines += [
            "",
            f"# {_one_line(cid)} — {title} [assurance={assurance}]",
            f"report.controls.exists(c, c.id == {_policy_string(cid)} && c.state in {states_list})",
        ]
    id_list = "[" + ", ".join(_policy_string(c) for c in ids) + "]"
    lines += [
        "",
        "# ALL — every profile control present and in a passing state",
        f"{id_list}.all(id, report.controls.exists(c, c.id == id && c.state in {states_list}))",
    ]
    return "\n".join(lines) + "\n"


_RENDERERS: dict[str, Callable[[ProfileSpec, dict[str, ControlSpec]], str]] = {
    "rego": _render_rego,
    "cel": _render_cel,
}


# --- Lightweight syntactic validation (deep validation is the engine's job) -


def _validate_rego(text: str) -> list[str]:
    errs: list[str] = []
    if "package osspolicykit" not in text:
        errs.append("rego: missing 'package osspolicykit' header")
    if text.count("{") != text.count("}"):
        errs.append("rego: unbalanced braces")
    return errs


def _validate_cel(text: str) -> list[str]:
    errs: list[str] = []
    if "FIDELITY BOUNDARY" not in text:
        errs.append("cel: missing fidelity-boundary header")
    if text.count("(") != text.count(")"):
        errs.append("cel: unbalanced parentheses")
    exprs = [ln for ln in text.splitlines() if ln.strip() and not ln.lstrip().startswith("#")]
    if not exprs:
        errs.append("cel: no expressions emitted")
    return errs


_VALIDATORS: dict[str, Callable[[str], list[str]]] = {
    "rego": _validate_rego,
    "cel": _validate_cel,
}


def _validate(text: str, fmt: str) -> list[str]:
    """Dispatch lightweight syntactic validation (empty list = no problems found)."""
    validator = _VALIDATORS.get(fmt)
    return validator(text) if validator is not None else []


def _run_export_policy(profile: str, fmt: str, output: Path | None, kit_root: Path | None, validate: bool) -> None:
    fmt_norm = fmt.lower().strip()
    if fmt_norm not in _RENDERERS:
        raise InvalidInputError(f"Unsupported --format {fmt!r}. Supported: {', '.join(_SUPPORTED_FORMATS)}.")

    root = merge_kit_root(kit_root)
    catalog = load_catalog(root / "controls" / "catalog.yaml")
    prof = load_profile_by_id(root, profile)
    rendered = _RENDERERS[fmt_norm](prof, catalog)

    if validate:
        errs = _validate(rendered, fmt_norm)
        if errs:
            c = stderr_console()
            for e in errs:
                c.print(f"[red]export-policy validation error:[/red] {e}")
            raise typer.Exit(code=1)

    out_path = output if output is not None else _DEFAULT_OUTPUT_BY_FORMAT[fmt_norm]
    try:
        out_path.write_text(rendered, encoding="utf-8")
    except OSError as exc:
        # A bad --output (existing directory, a path under a file, or a read-only
        # location) is a usage error, not an internal crash. Map it to exit 2 and
        # echo only exc.strerror so the absolute path / username is never leaked
        # (M-002), mirroring emit-insights / correlate-findings / export-evidence.
        raise InvalidInputError(f"Cannot write --output: {exc.strerror or 'filesystem error'}") from exc
    control_count = len(_sorted_profile_control_ids(prof))
    write_stdout_text(
        f"export-policy: wrote {out_path} (format={fmt_norm}, profile={prof.id}, controls={control_count})\n"
    )


@app.command("export-policy", rich_help_panel=CMD_PANEL_EXPORT)
def export_policy_cmd(
    profile: str = typer.Option(
        ...,
        "--profile",
        "-p",
        help="Profile id (or path to a profile YAML) to render into a policy skeleton.",
    ),
    fmt: str = typer.Option(
        "rego",
        "--format",
        help=f"Policy format. Supported: {', '.join(_SUPPORTED_FORMATS)}.",
    ),
    output: Path = typer.Option(
        None,
        "--output",
        "-o",
        help="Path to write the rendered policy. Defaults to policy.<format>.",
    ),
    kit_root: Path = typer.Option(
        None,
        "--kit-root",
        help="Override the bundled kit data root (controls/ + profiles/).",
    ),
    validate: bool = typer.Option(
        False,
        "--validate",
        help="Lightweight syntactic check before writing. Exit 1 on failure.",
    ),
) -> None:
    """Render a profile into a best-effort OPA/Rego or CEL policy skeleton (ADR-035).

    The generated policy is an integration shim that checks a kit
    ``evaluation-report.json`` (reports/2.0); it does not re-implement the kit's
    evaluators. See the fidelity-boundary header in the generated file.
    """
    try:
        _run_export_policy(profile, fmt, output, kit_root, validate)
    except OssPolicyKitError as exc:
        stderr_console().print(f"[red]Error:[/red] {markup_safe(exc.message)}")
        raise typer.Exit(code=2) from exc
    except typer.Exit:
        raise
    # Last-resort user message, no traceback leak.
    except Exception as exc:  # noqa: BLE001
        exit_for_unexpected(exc)
